### ISSUE TITLE
FEATURE: Add cartoon storke tower image to navbar

### ISSUE THREAD

**Issue by andrewpengucsb** [ucsb-cs156/proj-gauchoride#42]
As seen in the courses app [here](https://proj-courses.dokku-00.cs.ucsb.edu/), add the cartoon storke image to the nav bar. Found here: https://www.as.ucsb.edu/sticker-packs/

- [ ] Add the image to the nav bar
- [ ] Add footer text

**Comment by pconrad** [comment]
closed by #51
