### ISSUE TITLE
FEATURE: Change color of color navbar to UCSB's color's

### ISSUE THREAD

**Issue by bzamora020** [ucsb-cs156/proj-gauchoride#43]
### Have you updated the title?

- [ ] I have updated the issue's title.

### As a...

user

### I can...

see a navbar which has UCSB's blue color

### So that...

The navbar has more of a gaucho feeling

### Discussion

The navbar currently, has this color:
<img width="450" alt="image" src="https://github.com/ucsb-cs156/proj-gauchoride/assets/33767941/8b010b78-ee4e-4bc1-89e0-d4fd3b7a9a3b">

It would be nicer if it would have UCSB's official blue color to provide it more of a gaucho feeling:

<img width="189" alt="image" src="https://github.com/ucsb-cs156/proj-gauchoride/assets/33767941/67d9b32d-43e9-4024-9114-358a1eb9599b">

Hex color:
#003660

### Acceptance Criteria

- [ ] The navbar has the Navy blue UCSB color: #003660

### Implementation Todos

Frontend:
- [ ] Change the styling of the navbar color

**Comment by pconrad** [comment]
closed by #51
