### ISSUE TITLE
FEATURE: CRUD operations for Driver Shift table

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156/proj-gauchoride#44]
# User Story

* As a driver or admin
* I can do CRUD operations on the driver shift table
* so that drivers and admins can organize who is covering what shifts

## Note: This epic is already in progress

This epic was partially completed by the S23 students, but is not finished.  You will need to look over the epic description, assess which parts are complete, and which parts still need to be done.  Then you should complete the unfinished parts.  This may require adjustments to the parts that the S23 students did; feel free to make those adjustments if needed, but try to use as much of their work as you can to save yourself time and effort.

You may encounter situations like this in industry too, e.g. you may be asked to take over a partially completed for someone that is being reassigned to another team, going on medical leave, or leaving the company to take another job.   So learning how to assess what's been done and "jump in" is a very "real world" scenario to get some practice with.

### Discussion

This table was in the spreadsheet provided by Mike Fogelsanger on 05/17/23:

<img width="684" alt="image" src="https://github.com/ucsb-cs156/proj-gauchoride/assets/1119017/e89ed3fc-4236-46a6-9420-235f2dad4ead">

Each row shows a shift for a driver, with a day, start time, and end time.

Ideally, these rows should be connected to the user id of the driver.

### Acceptance Criteria

- [x] Drivers can do CRUD operations on their own rows in this table
- [x] Drivers can see all of the shifts, but can only edit/delete their own shifts.
       - Note: in MVP, it's ok if the buttons still appears, as long as when the user tries to click on them, they get an error instead of the row being deleted or edited.   Later on, we can add additional issues to make the buttons not appear, or be greyed out when they are not applicable for a given row.
- [x] Admins can edit or delete any shifts.
- [x] Riders have read only access to this table.

### Implementation Todos

Note that the backend feature may already be in place; but double check that this is true.
- [x] `@Entity` and `@Repository` classes for database table 
- [x] Backend endpoints for CRUD operations for the table

Some of these Frontend feature may already be done as well, but some are not:

- [x] Form component for data entry
- [x] Table component for displaying the table
- [x] IndexPage page component
- [x] CreatePage page component
- [x] EditPage page component

**Comment by pconrad** [comment]
This Epic is worth at least 20 points.   As it is a priority issue, if a team fails to complete it, up to 20 points may be deducted from the project grade for that team.

**Comment by Mohamed-Elfouly** [comment]
Was merged from m23-9am-2.
