### ISSUE TITLE
REFACTOR: Migrate from SpringFox to SpringDoc for Swagger

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156/proj-gauchoride#52]
### Discussion

We need to migrate the code base from SpringFox to SpringDoc for Swagger.

See: https://ucsb-cs156.github.io/topics/swagger/springfox_to_springdoc.html for more details.

As an example of a similar PR, you may consult: https://github.com/ucsb-cs156/proj-happycows/pull/60/files

### Acceptance Criteria

- [x] Swagger works properly
- [x] The code base uses only Springdoc, not Springfox

### Implementation Todos

Follow the plan here: https://ucsb-cs156.github.io/topics/swagger/springfox_to_springdoc.html

**Comment by ColinBaylis** [comment]
Has been completed and merged to main.
